apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: NodeApp
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - name: backend
      protocol: TCP
      port: 3080
      targetPort: 3080
      nodePort: 30748
    # - name: db
    #   protocol: TCP
    #   port: 27017
    #   targetPort: 27017
    # - name: frontend
    #   protocol: TCP
    #   port: 3000
    #   targetPort: 3000
      